### ISSUE TITLE
Error while testing the model

### ISSUE THREAD

**Issue by tomshalini** [mit-han-lab/lite-transformer#29]
Hello,

I tried evaluating the model.  I am getting following error:

Traceback (most recent call last):                                                                                                                                                        
  File "generate.py", line 191, in <module>
    cli_main()
  File "generate.py", line 187, in cli_main
    main(args)
  File "generate.py", line 105, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/shalinis/lite-transformer/fairseq/tasks/fairseq_task.py", line 246, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/shalinis/lite-transformer/fairseq/sequence_generator.py", line 146, in generate
    encoder_outs = model.forward_encoder(encoder_input)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/shalinis/lite-transformer/fairseq/sequence_generator.py", line 539, in forward_encoder
    return [model.encoder(**encoder_input) for model in self.models]
  File "/home/shalinis/lite-transformer/fairseq/sequence_generator.py", line 539, in <listcomp>
    return [model.encoder(**encoder_input) for model in self.models]
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shalinis/lite-transformer/fairseq/models/transformer_multibranch_v2.py", line 314, in forward
    x = layer(x, encoder_padding_mask)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shalinis/lite-transformer/fairseq/models/transformer_multibranch_v2.py", line 693, in forward
    x, _ = self.self_attn(query=x, key=x, value=x, key_padding_mask=encoder_padding_mask)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shalinis/lite-transformer/fairseq/modules/multibranch.py", line 37, in forward
    x = branch(q.contiguous(), incremental_state=incremental_state)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shalinis/lite-transformer/fairseq/modules/dynamicconv_layer/dynamicconv_layer.py", line 131, in forward
    output = self.linear2(output)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/shalinis/.conda/envs/integration/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
**RuntimeError: CUDA error: no kernel image is available for execution on the device**
Namespace(ignore_case=False, order=4, ref='/home/shalinis/lite-transformer/checkpoints/wmt14.en-fr/attention/multibranch_v2/embed496//exp/test_gen.out.ref', sacrebleu=False, sentence_bleu=False, sys='/home/shalinis/lite-transformer/checkpoints/wmt14.en-fr/attention/multibranch_v2/embed496//exp/test_gen.out.sys')
Traceback (most recent call last):
  File "score.py", line 88, in <module>
    main()
  File "score.py", line 84, in main
    score(f)
  File "score.py", line 78, in score
    print(scorer.result_string(args.order))
  File "/home/shalinis/lite-transformer/fairseq/bleu.py", line 127, in result_string
    return fmt.format(order, self.score(order=order), *bleup,
  File "/home/shalinis/lite-transformer/fairseq/bleu.py", line 103, in score
    return self.brevity() * math.exp(psum / order) * 100
  File "/home/shalinis/lite-transformer/fairseq/bleu.py", line 117, in brevity
    r = self.stat.reflen // self.stat.predlen
ZeroDivisionError: integer division or modulo by zero

**Kindly help me in resolving the same.**

**Comment by swgu98** [comment]
ZeroDivisionError: integer division or modulo by zero
I have this error, too.
RuntimeError: result type Float can't be cast to the desired output type Long
This is another error.They all happened during the test.

**Comment by realzza** [comment]
> RuntimeError: result type Float can't be cast to the desired output type Long

Indeed, I got this error too. Anyone have an idea how to solve this?

**Comment by Michaelvll** [comment]
Hi,
Thank you for asking! Could you please check if there is an output file at `$checkpoints_path/exp/test_gen.out`? The test.sh will first generate the output file for the test dataset using the model, and then use the score.py to evaluate the generated file with the ground truth. If the file is generated correctly, there will be a `ZeroDivisionError` since no input is fed into the `score.py`.

**Comment by realzza** [comment]
> > RuntimeError: result type Float can't be cast to the desired output type Long
> 
> Indeed, I got this error too. Anyone have an idea how to solve this?

I solved this error by changing `torch.div` into `torch.floor_divide`. This has been mentioned in a previous fairseq issue https://github.com/pytorch/fairseq/issues/2544.

**Comment by Gsw511** [comment]
> Hi,
> Thank you for asking! Could you please check if there is an output file at `$checkpoints_path/exp/test_gen.out`? The test.sh will first generate the output file for the test dataset using the model, and then use the score.py to evaluate the generated file with the ground truth. If the file is generated correctly, there will be a `ZeroDivisionError` since no input is fed into the `score.py`.

yeah, both  test_gen.out.ref  and  test_gen.out.sys  are  empty

**Comment by Michaelvll** [comment]
> > > RuntimeError: result type Float can't be cast to the desired output type Long
> > 
> > 
> > Indeed, I got this error too. Anyone have an idea how to solve this?
> 
> I solved this error by changing `torch.div` into `torch.floor_divide`. This has been mentioned in a previous fairseq issue [pytorch/fairseq#2544](https://github.com/pytorch/fairseq/issues/2544).

Thank you for fixing it! Could you please send a PR for that? : )

**Comment by swgu98** [comment]
> > > RuntimeError: result type Float can't be cast to the desired output type Long
> > 
> > 
> > Indeed, I got this error too. Anyone have an idea how to solve this?
> 
> I solved this error by changing `torch.div` into `torch.floor_divide`. This has been mentioned in a previous fairseq issue [pytorch/fairseq#2544](https://github.com/pytorch/fairseq/issues/2544).

Thank you! But  another warnning:
lite-transformer-master/fairseq/sequence_generator.py:397: UserWarning: An output with one or more elements was resized since it had shape [7], which does not match the required output shape [2].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/Resize.cpp:19.)
  torch.masked_select(

**Comment by realzza** [comment]
> > > > RuntimeError: result type Float can't be cast to the desired output type Long
> > > 
> > > 
> > > Indeed, I got this error too. Anyone have an idea how to solve this?
> > 
> > 
> > I solved this error by changing `torch.div` into `torch.floor_divide`. This has been mentioned in a previous fairseq issue [pytorch/fairseq#2544](https://github.com/pytorch/fairseq/issues/2544).
> 
> Thank you for fixing it! Could you please send a PR for that? : )

No Prob! PR has been made.

**Comment by Michaelvll** [comment]
Thanks to @ziangzhou-duke. The problem is solved in https://github.com/mit-han-lab/lite-transformer/pull/32.
